version: '3'

volumes:
  database_mysql_data: {}

networks:
  database_mysql_network:
    driver: bridge

services: 
  database:
    build: 
      context: .
      dockerfile: ./compose/database/Dockerfile
    image: sequelize_local_database
    restart: always
    container_name: database
    volumes:
      - database_mysql_data:/var/lib/mysql
    env_file:
      - ./.envs/.local/.database
    networks:
      - database_mysql_network
    ports:
      - 3389:3306
